import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Header
    'menu': 'Menu',
    'home': 'Home',
    'back': 'Back',
    
    // Navigation
    'beverages': 'BEVERAGES',
    'food': 'FOOD', 
    'shisha': 'SHISHA',
    'signatures': 'SIGNATURES',
    
    // Beverage Categories
    'hot-drinks': 'HOT DRINKS',
    'cold-coffee': 'COLD COFFEE',
    'fresh-juice': 'FRESH JUICE',
    'soft-drinks': 'SOFT DRINKS',
    'frappe': 'FRAPPE',
    'milkshake': 'MILK SHAKE',
    'smoothies': 'SMOOTHIES',
    'mojito': 'MOJITO',
    'iced-tea': 'ICED TEA',
    'non-coffee': 'NON-COFFEE',
    
    // Food Categories
    'breakfast': 'BREAKFAST',
    'pizza': 'PIZZA',
    'sandwiches': 'SANDWICHES',
    'italian': 'ITALIAN',
    'main-course': 'MAIN COURSE',
    'appetizers': 'APPETIZERS',
    'salads': 'SALADS',
    'soup': 'SOUP',
    'desserts': 'DESSERTS',
    
    // Shisha Categories
    'regular': 'REGULAR SHISHA',
    'premium': 'PREMIUM SHISHA',
    'special': 'SPECIAL SHISHA',
    
    // Menu Labels
    'drinks-menu': 'DRINKS MENU',
    'food-menu': 'FOOD MENU',
    'shisha-menu': 'SHISHA MENU',
    
    // Product Details
    'description': 'Description',
    'price': 'Price',
    'category': 'Category',
    
    // Common
    'welcome': 'Welcome to The Oak Cafe',
    'premium-experience': 'Premium Middle Eastern Experience',
    'oak-cafe': 'Oak Cafe',
    
    // Product Names - Beverages
    'red-eye': 'Red Eye',
    'v60': 'V60',
    'chemex': 'Chemex',
    'flat-white': 'Flat White',
    'espresso-macchiato': 'Espresso Macchiato',
    'oak-seasonal-juice': 'The Oak Seasonal Fresh Juice',
    'turkish-coffee-single': 'Turkish Coffee Single',
    'double-espresso': 'Double Espresso',
    'cappuccino': 'Cappuccino',
    'cortado': 'Cortado',
    'latte': 'Latte',
    'americano': 'Americano',
    'turkish-coffee-double': 'Turkish Coffee Double',
    'iced-caramel-macchiato': 'Iced Caramel Macchiato',
    'cold-brew': 'Cold Brew',
    'iced-dark-mocha': 'Iced Dark Mocha',
    'iced-americano': 'Iced Americano',
    'pomegranate': 'Pomegranate',
    'mango-mint': 'Mango Mint',
    'orange-juice': 'Orange Juice',
    'coca-cola': 'Coca Cola',
    'sprite': 'Sprite',
    'red-bull': 'Red Bull',
    'affogato': 'Affogato',
    'apple-juice': 'Apple Juice',
    'carrot-juice': 'Carrot Juice',
    
    // NEW BEVERAGE ITEMS - ALL MISSING TRANSLATIONS
    'v60-chemex': 'V60 / CHEMEX',
    'marshmallow-chocolate': 'Marshmallow Chocolate',
    'caramel-macchiato': 'Caramel Macchiato',
    'lungo': 'Lungo',
    'white-coffee': 'White Coffee',
    'sandy-chocolate': 'Sandy Chocolate',
    'filter-coffee': 'Filter Coffee',
    'white-mocha': 'White Mocha',
    'chili-chocolate': 'Chili Chocolate',
    'spanish-latte': 'Spanish Latte',
    'dark-mocha': 'Dark Mocha',
    'iced-flat-white': 'Iced Flat White',
    'iced-white-mocha': 'Iced White Mocha',
    'iced-latte': 'Iced Latte',
    'iced-spanish-latte': 'Iced Spanish Latte',
    'hazelnut-frappe': 'Hazelnut Frappe',
    'white-fruit-frappe': 'White Fruit Frappe',
    'white-chocolate-frappe': 'White Chocolate Frappe',
    'chocolate-frappe': 'Chocolate Frappe',
    'coffee-frappe': 'Coffee Frappe',
    'arabia-milkshake': 'Arabia Milkshake',
    'lemon-milkshake': 'Lemon Milkshake',
    'mango-milkshake': 'Mango Milkshake',
    'mix-berries-smoothie': 'Mix Berries Smoothie',
    'lemonade-smoothie': 'Lemonade Smoothie',
    'mango-passionfruit-smoothie': 'Mango and Passionfruit Smoothie',
    'lemon-mint-smoothie': 'Lemon with Mint Smoothie',
    'basil-lemonade-smoothie': 'Basil Lemonade Smoothie',
    'orange-smoothie': 'Orange Smoothie',
    'mango-mint-juice': 'Mango Mint Juice',
    'basil-lemonade-juice': 'Basil Lemonade Juice',
    'lemon-mint-juice': 'Lemon with Mint Juice',
    'lemonade-juice': 'Lemonade Juice',
    'pomegranate-juice': 'Pomegranate Juice',
    'mango-basil-juice': 'Mango Basil Juice',
    'forest-mojito': 'Forest Mojito',
    'mango-mojito': 'Mango Mojito',
    'pink-lemonade': 'Pink Lemonade',
    'red-sea-redbull': 'Red Sea Red Bull',
    'maldives-redbull': 'Maldives Red Bull',
    'ice-tea-peach': 'Ice Tea Peach',
    'iced-tea-mango': 'Iced Tea Mango',
    'iced-tea-sugar-free': 'Iced Tea Sugar Free',
    'iced-tea-strawberry': 'Iced Tea Strawberry',
    'iced-tea-grenadine': 'Iced Tea Grenadine',
    'ice-tea-forest': 'Ice Tea Forest',
    'ice-tea-passion-fruit': 'Ice Tea Passion Fruit',
    'black-tea': 'Black Tea',
    'matcha': 'Matcha',
    'special-tea': 'Special Tea',
    'green-tea': 'Green Tea',
    'chai-latte-vanilla': 'Chai Latte Vanilla',
    'chai-latte-spiced': 'Chai Latte Spiced',
    'hot-chocolate': 'Hot Chocolate',
    'coca-cola-zero': 'Coca Cola Zero',
    'redbull-sugar-free': 'Red Bull Sugar Free',
    'sprite-zero': 'Sprite Zero',
    'perrier': 'Perrier',
    'mineral-water': 'Mineral Water',
    
    // Food Names
    'eggs-of-your-choice': 'Eggs of Your Choice',
    'halloumi-croissant': 'Halloumi Croissant',
    'tuna-sandwich': 'Tuna Sandwich',
    'manakish-labneh-rocca': 'Manakish Labneh and Rocca',
    'turkey-omelette-croissant': 'Turkey Omelette Croissant',
    'zaatar-pomegranate': 'Zaatar and Pomegranate',
    'marshmallow-hot-chocolate': 'Marshmallow Hot Chocolate',
    
    // Product Descriptions
    'red-eye-desc': 'Strong coffee with espresso shot',
    'v60-desc': 'Pour-over specialty coffee',
    'flat-white-desc': 'Smooth espresso with steamed milk and minimal foam',
    'espresso-macchiato-desc': 'Espresso with steamed milk foam',
    'marshmallow-hot-chocolate-desc': 'Rich hot chocolate with marshmallows',
    'related-products': 'RELATED PRODUCTS',
    'oak-beef-burger': 'OAK Beef Burger',
    'oak-beef-burger-desc': 'Premium beef burger with fresh vegetables and our signature sauce',
    'club-sandwich': 'Club Sandwich',
    'club-sandwich-desc': 'Classic club sandwich with turkey, bacon, lettuce, and tomato on toasted bread',
    'chicken-sandwich': 'Chicken Sandwich',
    'chicken-sandwich-desc': 'Grilled chicken breast sandwich with fresh vegetables and special sauce',
    'eggs-of-your-choice-desc': 'Fresh eggs prepared exactly how you like them',
    'halloumi-croissant-desc': 'Buttery croissant filled with grilled halloumi cheese',
    'tuna-sandwich-desc': 'Fresh tuna salad sandwich with crisp vegetables',
    'oak-sandwich': 'The Oak Sandwich',
    'oak-sandwich-desc': 'Our signature sandwich with premium ingredients',
    'shawarma-meat': 'Shawarma Meat',
    'shawarma-meat-desc': 'Traditional Middle Eastern shawarma with seasoned meat',
    'crispy-chicken-burger': 'Crispy Chicken Burger',
    'crispy-chicken-burger-desc': 'Crispy fried chicken burger with fresh toppings',
    'manakish-labneh-rocca-desc': 'Traditional Middle Eastern flatbread with labneh and rocket leaves',
    'turkey-omelette-croissant-desc': 'Fluffy croissant with turkey omelette filling',
    'zaatar-pomegranate-desc': 'Traditional zaatar bread topped with fresh pomegranate seeds',
    'pizza-margherita': 'Pizza Margherita',
    'pizza-margherita-desc': 'Classic Italian pizza with fresh mozzarella, tomato, and basil',
    'chicken-bbq-pizza': 'Chicken BBQ Pizza',
    'chicken-bbq-pizza-desc': 'BBQ chicken pizza with tender chicken and barbecue sauce',
    'turkish-coffee-single-desc': 'Traditional Turkish coffee prepared in authentic copper pot',
    'double-espresso-desc': 'Double shot of rich espresso for the ultimate coffee experience',
    'grilled-cheese-desc': 'Golden grilled cheese sandwich with melted cheese and crispy bread',
    'seafood-pasta': 'Seafood Pasta',
    'seafood-pasta-desc': 'Fresh seafood pasta with mixed ocean delights',
    'spaghetti-bolognese': 'Spaghetti Bolognese',
    'spaghetti-bolognese-desc': 'Traditional Italian spaghetti with rich meat sauce',
    'fettuccine-alfredo': 'Fettuccine Alfredo',
    'fettuccine-alfredo-desc': 'Creamy fettuccine alfredo with parmesan cheese and butter sauce',
    'lasagna': 'Lasagna',
    'lasagna-desc': 'Traditional layered lasagna with meat, cheese, and tomato sauce',
    'spaghetti-carbonara': 'Spaghetti Carbonara',
    'spaghetti-carbonara-desc': 'Traditional Italian carbonara with eggs, cheese, pancetta, and black pepper',
    'risotto-mushroom': 'Risotto Mushroom',
    'risotto-mushroom-desc': 'Creamy mushroom risotto with arborio rice and mixed wild mushrooms',
    'chef-salad': 'Chef Salad',
    'chef-salad-desc': 'Fresh chef salad with mixed greens and chef selection',
    'greek-salad': 'Greek Salad',
    'greek-salad-desc': 'Traditional Greek salad with feta cheese, olives, and Mediterranean vegetables',
    'caesar-salad': 'Caesar Salad',
    'caesar-salad-desc': 'Classic Caesar salad with romaine lettuce, croutons, and parmesan cheese',
    'smoked-salmon-salad': 'Smoked Salmon Salad',
    'smoked-salmon-salad-desc': 'Premium smoked salmon salad with fresh greens',
    'mushroom-soup': 'Mushroom Soup',
    'mushroom-soup-desc': 'Creamy mushroom soup with fresh herbs and a touch of cream',
    'seafood-soup': 'Seafood Soup',
    'seafood-soup-desc': 'Rich seafood soup with fresh ocean ingredients',
    
    // Category Names
    'category-breakfast': 'BREAKFAST',
    'category-pizza': 'PIZZA',
    'category-sandwiches': 'SANDWICHES',
    'category-italian': 'ITALIAN',
    'category-salads': 'SALADS',
    'category-soup': 'SOUP',
    'category-desserts': 'DESSERTS',
    'category-hot-drinks': 'HOT DRINKS',
    'category-cold-drinks': 'COLD DRINKS',
    'category-frappe': 'FRAPPE',
    'category-milkshake': 'MILKSHAKE',
    'category-smoothies': 'SMOOTHIES',
    'category-mojito': 'MOJITO',
    'category-iced-tea': 'ICED TEA',
    'category-shisha': 'SHISHA',
    'category-cold-coffee': 'COLD COFFEE',
    'category-fresh-juice': 'FRESH JUICE',
    'category-main-course': 'MAIN COURSE',
    'category-premium': 'PREMIUM',
    'category-regular': 'REGULAR',
    'category-special': 'SPECIAL',
    'beverages-menu': 'BEVERAGES MENU',
    
    // Missing Food Items
    'mix-formaggio': 'Mix Formaggio',
    'mix-formaggio-desc': 'Mixed cheese pizza with four different types of cheese',
    'pizza-chicken-alfredo': 'Pizza Chicken Alfredo',
    'pizza-chicken-alfredo-desc': 'Creamy alfredo pizza topped with grilled chicken',
    'calzone-pizza': 'Calzone Pizza',
    'calzone-pizza-desc': 'Traditional Italian folded pizza with cheese and toppings',
    'pepperoni': 'Pepperoni',
    'pepperoni-desc': 'Classic pepperoni pizza with spicy pepperoni slices',
    'oak-steak': 'The Oak Steak',
    'oak-steak-desc': 'Premium beef steak grilled to perfection',
    'salmon-grill': 'Salmon Grill',
    'salmon-grill-desc': 'Fresh grilled salmon with herbs and lemon',
    'beef-steak': 'Beef Steak',
    'beef-steak-desc': 'Tender beef steak cooked to your preference',
    'chicken-mushroom': 'Chicken Mushroom',
    'chicken-mushroom-desc': 'Grilled chicken breast with mushroom sauce',
    'mix-platter': 'Mix Platter',
    'mix-platter-desc': 'Assorted appetizer platter with variety of Middle Eastern favorites',
    'mexican-nachos': 'Mexican Nachos',
    'mexican-nachos-desc': 'Crispy nachos with cheese, jalapeños, and Mexican spices',
    'dynamite-shrimp': 'Dynamite Shrimp',
    'dynamite-shrimp-desc': 'Spicy fried shrimp with dynamite sauce',
    'chicken-dynamite': 'Chicken Dynamite',
    'chicken-dynamite-desc': 'Crispy chicken pieces with spicy dynamite sauce',
    'san-sebastian-cake': 'San Sebastian Cake',
    'san-sebastian-cake-desc': 'Basque-style burnt cheesecake with rich creamy texture',
    'chocolate-cake': 'Chocolate Cake',
    'chocolate-cake-desc': 'Rich chocolate layer cake with chocolate frosting',
    'tiramisu': 'Tiramisu',
    'tiramisu-desc': 'Classic Italian dessert with coffee-soaked ladyfingers and mascarpone',
    'ice-cream-vanilla': 'Vanilla Ice Cream',
    'ice-cream-vanilla-desc': 'Premium vanilla ice cream with real vanilla beans',
    'ice-cream-chocolate': 'Chocolate Ice Cream',
    'ice-cream-chocolate-desc': 'Rich chocolate ice cream made with premium cocoa',
    'ice-cream-strawberry': 'Strawberry Ice Cream',
    'ice-cream-strawberry-desc': 'Fresh strawberry ice cream with real fruit pieces',
    'category-appetizers': 'APPETIZERS',
    'appetizers': 'APPETIZERS',
    'main-course': 'MAIN COURSE',
    'seafood-pasta-desc': 'Fresh pasta with mixed seafood in tomato sauce',
    'spaghetti-bolognese': 'Spaghetti Bolognese',
    'spaghetti-bolognese-desc': 'Classic Italian pasta with rich meat sauce',
    'lasagna': 'Lasagna',
    'lasagna-desc': 'Traditional layered pasta with meat sauce and cheese',
    'related-products': 'RELATED PRODUCTS',
    'drinks-menu': 'DRINKS MENU',
    'food-menu': 'FOOD MENU',
    'shisha-menu': 'SHISHA MENU',
    'regular-shisha': 'REGULAR SHISHA',
    'premium-shisha': 'PREMIUM SHISHA',
    'special-shisha': 'SPECIAL SHISHA',
    'fanta': 'Fanta',
    'caramel-frappe': 'Caramel Frappe',
    'vanilla-frappe': 'Vanilla Frappe',
    'chocolate-frappe': 'Chocolate Frappe',
    'strawberry-milkshake': 'Strawberry Milkshake',
    'vanilla-milkshake': 'Vanilla Milkshake',
    'chocolate-milkshake': 'Chocolate Milkshake',
    'mango-smoothie': 'Mango Smoothie',
    'berry-smoothie': 'Berry Smoothie',
    'green-smoothie': 'Green Smoothie',
    'classic-mojito': 'Classic Mojito',
    'strawberry-mojito': 'Strawberry Mojito',
    'berry-mojito': 'Berry Mojito',
    'passion-fruit-mojito': 'Passion Fruit Mojito',
    'classic-iced-tea': 'Classic Iced Tea',
    'lemon-iced-tea': 'Lemon Iced Tea',
    'peach-iced-tea': 'Peach Iced Tea',
    
    // Product Names - Food
    'eggs-of-your-choice': 'Eggs of Your Choice',
    'french-toast': 'French Toast',
    'pancakes': 'Pancakes',
    'margherita-pizza': 'Margherita Pizza',
    'pepperoni-pizza': 'Pepperoni Pizza',
    'quattro-stagioni': 'Quattro Stagioni',
    'chicken-wings': 'Chicken Wings',
    'mozzarella-sticks': 'Mozzarella Sticks',
    'mexican-nachos': 'Mexican Nachos',
    'dynamite-shrimp': 'Dynamite Shrimp',
    'chicken-dynamite': 'Chicken Dynamite',
    'san-sebastian-cake': 'San Sebastian Cake',
    'tiramisu-cake': 'Tiramisu Cake',
    'cheesecake': 'Cheesecake',
    'kenafa-naama': 'Kenafa Naama',
    'club-sandwich': 'Club Sandwich',
    'chicken-sandwich': 'Chicken Sandwich',
    'grilled-cheese': 'Grilled Cheese',
    'spaghetti-carbonara': 'Spaghetti Carbonara',
    'fettuccine-alfredo': 'Fettuccine Alfredo',
    'risotto-mushroom': 'Risotto Mushroom',
    'caesar-salad': 'Caesar Salad',
    'greek-salad': 'Greek Salad',
    'quinoa-salad': 'Quinoa Salad',
    'mushroom-soup': 'Mushroom Soup',
    'tomato-soup': 'Tomato Soup',
    'chicken-noodle-soup': 'Chicken Noodle Soup',
  },
  ar: {
    // Header
    'menu': 'القائمة',
    'home': 'الرئيسية',
    'back': 'رجوع',
    
    // Navigation
    'beverages': 'المشروبات',
    'food': 'الطعام',
    'shisha': 'الشيشة',
    'signatures': 'التوقيعات',
    
    // Beverage Categories
    'hot-drinks': 'المشروبات الساخنة',
    'cold-coffee': 'القهوة الباردة',
    'fresh-juice': 'العصائر الطازجة',
    'soft-drinks': 'المشروبات الغازية',
    'frappe': 'فرابيه',
    'milkshake': 'ميلك شيك',
    'smoothies': 'سموذي',
    'mojito': 'موهيتو',
    'iced-tea': 'الشاي المثلج',
    
    // Food Categories
    'breakfast': 'الإفطار',
    'pizza': 'البيتزا',
    'sandwiches': 'الساندويتشات',
    'italian': 'الإيطالي',
    'main-course': 'الأطباق الرئيسية',
    'appetizers': 'المقبلات',
    'salads': 'السلطات',
    'soup': 'الشوربة',
    'desserts': 'الحلويات',
    
    // Shisha Categories
    'regular': 'الشيشة العادية',
    'premium': 'الشيشة المميزة',
    'special': 'الشيشة الخاصة',
    
    // Menu Labels
    'drinks-menu': 'قائمة المشروبات',
    'food-menu': 'قائمة الطعام',
    'shisha-menu': 'قائمة الشيشة',
    
    // Product Details
    'description': 'الوصف',
    'price': 'السعر',
    'category': 'الفئة',
    
    // Common
    'welcome': 'مرحباً بكم في مقهى أوك',
    'premium-experience': 'تجربة شرق أوسطية مميزة',
    'oak-cafe': 'مقهى أوك',
    
    // Product Names - Beverages (Cultural Adaptations)
    'red-eye': 'قهوة ريد آي',
    'v60': 'قهوة مختصة في ٦٠',
    'chemex': 'قهوة كيمكس',
    'flat-white': 'قهوة فلات وايت',
    'espresso-macchiato': 'إسبريسو ماكياتو',
    'oak-seasonal-juice': 'عصير أوك الموسمي الطازج',
    'turkish-coffee-single': 'قهوة تركية مفردة',
    'double-espresso': 'إسبريسو مزدوج',
    'cappuccino': 'كابتشينو',
    'cortado': 'كورتادو',
    'latte': 'لاتيه',
    'americano': 'أمريكانو',
    'turkish-coffee-double': 'قهوة تركية مزدوجة',
    'iced-caramel-macchiato': 'ماكياتو كراميل مثلج',
    'cold-brew': 'قهوة باردة مختمرة',
    'iced-dark-mocha': 'موكا داكن مثلج',
    'iced-americano': 'أمريكانو مثلج',
    'pomegranate': 'رمان',
    'mango-mint': 'مانجو بالنعناع',
    'orange-juice': 'عصير برتقال',
    'coca-cola': 'كوكا كولا',
    'sprite': 'سبرايت',
    'red-bull': 'ريد بول',
    'affogato': 'أفوجاتو',
    'apple-juice': 'عصير تفاح',
    'carrot-juice': 'عصير جزر',
    
    // Food Names
    'eggs-of-your-choice': 'بيض حسب الطلب',
    'halloumi-croissant': 'كرواسان حلوم',
    'tuna-sandwich': 'ساندويش تونة',
    'manakish-labneh-rocca': 'مناقيش لبنة وجرجير',
    'turkey-omelette-croissant': 'كرواسان أومليت ديك رومي',
    'zaatar-pomegranate': 'زعتر ودبس رمان',
    'marshmallow-hot-chocolate': 'شوكولاتة ساخنة بالمارشملو',
    
    // Product Descriptions
    'red-eye-desc': 'قهوة قوية مع جرعة إسبريسو',
    'v60-desc': 'قهوة مختصة بالتقطير',
    'flat-white-desc': 'إسبريسو ناعم بحليب مبخر ورغوة قليلة',
    'espresso-macchiato-desc': 'إسبريسو برغوة حليب مبخرة',
    'marshmallow-hot-chocolate-desc': 'شوكولاتة ساخنة غنية بالمارشملو',
    'related-products': 'منتجات ذات صلة',
    'oak-beef-burger': 'برغر أوك اللحم البقري',
    'oak-beef-burger-desc': 'برغر لحم بقري فاخر مع خضار طازجة وصلصتنا المميزة',
    'club-sandwich': 'ساندويش كلوب',
    'club-sandwich-desc': 'ساندويش كلوب كلاسيكي مع الديك الرومي والبيكون والخس والطماطم',
    'chicken-sandwich': 'ساندويش دجاج',
    'chicken-sandwich-desc': 'ساندويش دجاج مشوي مع خضار طازجة وصلصة خاصة',
    'eggs-of-your-choice-desc': 'بيض طازج محضر كما تشاء تماماً',
    'halloumi-croissant': 'كرواسان حلومي',
    'halloumi-croissant-desc': 'كرواسان بالزبدة محشو بجبنة الحلومي المشوية',
    'tuna-sandwich': 'ساندويش تونة',
    'tuna-sandwich-desc': 'ساندويش سلطة تونة طازجة مع خضار مقرمشة',
    'oak-sandwich': 'ساندويش أوك',
    'oak-sandwich-desc': 'ساندويشنا المميز بمكونات فاخرة',
    'shawarma-meat': 'شاورما لحمة',
    'shawarma-meat-desc': 'شاورما شرق أوسطية تقليدية بلحم متبل',
    'crispy-chicken-burger': 'برغر دجاج مقرمش',
    'crispy-chicken-burger-desc': 'برغر دجاج مقلي مقرمش مع إضافات طازجة',
    'manakish-labneh-rocca-desc': 'خبز شرق أوسطي تقليدي باللبنة وأوراق الجرجير',
    'turkey-omelette-croissant-desc': 'كرواسان هش مع حشوة أومليت الديك الرومي',
    'zaatar-pomegranate-desc': 'خبز زعتر تقليدي مع حبوب الرمان الطازجة',
    'pizza-margherita': 'بيتزا مارغريتا',
    'pizza-margherita-desc': 'بيتزا إيطالية كلاسيكية بالموزاريلا الطازجة والطماطم والريحان',
    'chicken-bbq-pizza': 'بيتزا دجاج باربكيو',
    'chicken-bbq-pizza-desc': 'بيتزا دجاج بالباربكيو مع قطع الدجاج الطرية وصلصة الباربكيو',
    'turkish-coffee-single': 'قهوة تركية مفردة',
    'turkish-coffee-single-desc': 'قهوة تركية تقليدية محضرة في إبريق نحاسي أصيل',
    'double-espresso': 'إسبريسو مضاعف',
    'double-espresso-desc': 'جرعة مضاعفة من الإسبريسو الغني لتجربة القهوة المثلى',
    'grilled-cheese': 'جبن مشوي',
    'grilled-cheese-desc': 'ساندويش جبن مشوي ذهبي مع جبن مذاب وخبز مقرمش',
    'seafood-pasta': 'باستا مأكولات بحرية',
    'seafood-pasta-desc': 'باستا مأكولات بحرية طازجة مع مزيج من الثمار البحرية',
    'spaghetti-bolognese': 'سباغيتي بولونيز',
    'spaghetti-bolognese-desc': 'سباغيتي إيطالية تقليدية بصلصة اللحم الغنية',
    'fettuccine-alfredo': 'فيتوتشيني ألفريدو',
    'fettuccine-alfredo-desc': 'فيتوتشيني كريمية بجبن البارميزان وصلصة الزبدة',
    'lasagna': 'لازانيا',
    'lasagna-desc': 'لازانيا مطبقة تقليدية باللحم والجبن وصلصة الطماطم',
    'spaghetti-carbonara': 'سباغيتي كاربونارا',
    'spaghetti-carbonara-desc': 'كاربونارا إيطالية تقليدية بالبيض والجبن والبانشيتا والفلفل الأسود',
    'risotto-mushroom': 'ريزوتو فطر',
    'risotto-mushroom-desc': 'ريزوتو فطر كريمي مع أرز الأربوريو والفطر البري المتنوع',
    'chef-salad': 'سلطة الشيف',
    'chef-salad-desc': 'سلطة الشيف الطازجة مع الخضار المشكلة واختيار الشيف',
    'greek-salad': 'سلطة يونانية',
    'greek-salad-desc': 'سلطة يونانية تقليدية مع جبن الفيتا والزيتون والخضار المتوسطية',
    'caesar-salad': 'سلطة قيصر',
    'caesar-salad-desc': 'سلطة قيصر كلاسيكية مع خس الرومين والخبز المحمص وجبن البارميزان',
    'smoked-salmon-salad': 'سلطة سلمون مدخن',
    'smoked-salmon-salad-desc': 'سلطة سلمون مدخن فاخرة مع الخضار الطازجة',
    'mushroom-soup': 'شوربة فطر',
    'mushroom-soup-desc': 'شوربة فطر كريمية بالأعشاب الطازجة ولمسة من الكريمة',
    'seafood-soup': 'شوربة مأكولات بحرية',
    'seafood-soup-desc': 'شوربة مأكولات بحرية غنية بالمكونات البحرية الطازجة',
    
    // Category Names in Arabic
    'category-breakfast': 'الإفطار',
    'category-pizza': 'البيتزا',
    'category-sandwiches': 'الساندويشات',
    'category-italian': 'الأطباق الإيطالية',
    'category-salads': 'السلطات',
    'category-soup': 'الشوربات',
    'category-desserts': 'الحلويات',
    'category-hot-drinks': 'المشروبات الساخنة',
    'category-cold-drinks': 'المشروبات الباردة',
    'category-frappe': 'الفرابيه',
    'category-milkshake': 'الميلك شيك',
    'category-smoothies': 'السموثي',
    'category-mojito': 'الموخيتو',
    'category-iced-tea': 'الشاي المثلج',
    'category-shisha': 'الشيشة',
    'category-cold-coffee': 'القهوة الباردة',
    'category-fresh-juice': 'العصائر الطازجة',
    'category-main-course': 'الأطباق الرئيسية',
    'category-premium': 'بريميوم',
    'category-regular': 'عادي',
    'category-special': 'خاص',
    'food-menu': 'قائمة الطعام',
    'beverages-menu': 'قائمة المشروبات',
    
    // Missing Food Items in Arabic
    'mix-formaggio': 'ميكس فورماجيو',
    'mix-formaggio-desc': 'بيتزا الجبن المشكل مع أربعة أنواع مختلفة من الجبن',
    'pizza-chicken-alfredo': 'بيتزا دجاج ألفريدو',
    'pizza-chicken-alfredo-desc': 'بيتزا ألفريدو الكريمية مع الدجاج المشوي',
    'calzone-pizza': 'كالزونيه بيتزا',
    'calzone-pizza-desc': 'بيتزا إيطالية تقليدية مطوية مع الجبن والحشوات',
    'pepperoni': 'بيبروني',
    'pepperoni-desc': 'بيتزا بيبروني كلاسيكية مع شرائح البيبروني الحارة',
    'oak-steak': 'ستيك الأوك',
    'oak-steak-desc': 'ستيك لحم بقري فاخر مشوي للكمال',
    'salmon-grill': 'سلمون مشوي',
    'salmon-grill-desc': 'سلمون طازج مشوي بالأعشاب والليمون',
    'beef-steak': 'ستيك لحم بقري',
    'beef-steak-desc': 'ستيك لحم بقري طري مطبوخ حسب تفضيلك',
    'chicken-mushroom': 'دجاج بالفطر',
    'chicken-mushroom-desc': 'صدر دجاج مشوي مع صلصة الفطر',
    'mix-platter': 'طبق مشكل',
    'mix-platter-desc': 'طبق مقبلات متنوع مع مجموعة من المفضلات الشرق أوسطية',
    'mexican-nachos': 'ناتشوز مكسيكية',
    'mexican-nachos-desc': 'ناتشوز مقرمشة مع الجبن والهالابينو والتوابل المكسيكية',
    'dynamite-shrimp': 'جمبري ديناميت',
    'dynamite-shrimp-desc': 'جمبري مقلي حار مع صلصة الديناميت',
    'chicken-dynamite': 'دجاج ديناميت',
    'chicken-dynamite-desc': 'قطع دجاج مقرمشة مع صلصة الديناميت الحارة',
    'san-sebastian-cake': 'كيك سان سيباستيان',
    'san-sebastian-cake-desc': 'تشيز كيك محروقة على الطريقة الباسكية بقوام كريمي غني',
    'chocolate-cake': 'كيك الشوكولاتة',
    'chocolate-cake-desc': 'كيك الشوكولاتة الغنية بطبقات مع كريمة الشوكولاتة',
    'tiramisu': 'تيراميسو',
    'tiramisu-desc': 'حلوى إيطالية كلاسيكية مع أصابع السيدة المنقوعة بالقهوة والماسكاربوني',
    'ice-cream-vanilla': 'آيس كريم فانيلا',
    'ice-cream-vanilla-desc': 'آيس كريم فانيلا فاخر مع حبوب الفانيلا الحقيقية',
    'ice-cream-chocolate': 'آيس كريم شوكولاتة',
    'ice-cream-chocolate-desc': 'آيس كريم شوكولاتة غني مصنوع من الكاكاو الفاخر',
    'ice-cream-strawberry': 'آيس كريم فراولة',
    'ice-cream-strawberry-desc': 'آيس كريم فراولة طازج مع قطع الفاكهة الحقيقية',
    'category-appetizers': 'المقبلات',
    'appetizers': 'المقبلات',
    'main-course': 'الأطباق الرئيسية',
    'seafood-pasta': 'باستا بحرية',
    'seafood-pasta-desc': 'باستا طازجة مع المأكولات البحرية المشكلة بصلصة الطماطم',
    'spaghetti-bolognese': 'سباغيتي بولونيز',
    'spaghetti-bolognese-desc': 'باستا إيطالية كلاسيكية مع صلصة اللحم الغنية',
    'lasagna': 'لازانيا',
    'lasagna-desc': 'باستا طبقات تقليدية مع صلصة اللحم والجبن',
    'related-products': 'المنتجات ذات الصلة',
    'drinks-menu': 'قائمة المشروبات',
    'food-menu': 'قائمة الطعام',
    'shisha-menu': 'قائمة الشيشة',
    'regular-shisha': 'شيشة عادية',
    'premium-shisha': 'شيشة مميزة',
    'special-shisha': 'شيشة خاصة',
    'fanta': 'فانتا',
    'caramel-frappe': 'فرابيه كراميل',
    'vanilla-frappe': 'فرابيه فانيلا',
    'chocolate-frappe': 'فرابيه شوكولاتة',
    'strawberry-milkshake': 'ميلك شيك فراولة',
    'vanilla-milkshake': 'ميلك شيك فانيلا',
    'chocolate-milkshake': 'ميلك شيك شوكولاتة',
    'mango-smoothie': 'سموذي مانجو',
    'berry-smoothie': 'سموذي توت',
    'green-smoothie': 'سموذي أخضر',
    'classic-mojito': 'موهيتو كلاسيكي',
    'strawberry-mojito': 'موهيتو فراولة',
    'berry-mojito': 'موهيتو توت',
    'passion-fruit-mojito': 'موهيتو فاكهة العاطفة',
    'classic-iced-tea': 'شاي مثلج كلاسيكي',
    'lemon-iced-tea': 'شاي مثلج بالليمون',
    'peach-iced-tea': 'شاي مثلج بالخوخ',
    
    // NEW BEVERAGE ITEMS ARABIC TRANSLATIONS
    'v60-chemex': 'في ٦٠ / كيمكس',
    'marshmallow-chocolate': 'شوكولاتة مارشمالو',
    'caramel-macchiato': 'كاراميل ماكياتو',
    'lungo': 'لونغو',
    'white-coffee': 'قهوة بيضاء',
    'sandy-chocolate': 'شوكولاتة رملية',
    'filter-coffee': 'قهوة مفلترة',
    'white-mocha': 'موكا بيضاء',
    'chili-chocolate': 'شوكولاتة حارة',
    'spanish-latte': 'لاتيه إسباني',
    'dark-mocha': 'موكا داكنة',
    'iced-flat-white': 'فلات وايت مثلج',
    'iced-white-mocha': 'موكا بيضاء مثلجة',
    'iced-latte': 'لاتيه مثلج',
    'iced-spanish-latte': 'لاتيه إسباني مثلج',
    'hazelnut-frappe': 'فرابيه بندق',
    'white-fruit-frappe': 'فرابيه فواكه بيضاء',
    'white-chocolate-frappe': 'فرابيه شوكولاتة بيضاء',
    'coffee-frappe': 'فرابيه قهوة',
    'arabia-milkshake': 'ميلك شيك عربيا',
    'lemon-milkshake': 'ميلك شيك ليمون',
    'mango-milkshake': 'ميلك شيك مانجو',
    'mix-berries-smoothie': 'سموذي توت مشكل',
    'lemonade-smoothie': 'سموذي ليمونادا',
    'mango-passionfruit-smoothie': 'سموذي مانجو وفاكهة العاطفة',
    'lemon-mint-smoothie': 'سموذي ليمون ونعناع',
    'basil-lemonade-smoothie': 'سموذي ليمونادا بالريحان',
    'orange-smoothie': 'سموذي برتقال',
    'mango-mint-juice': 'عصير مانجو ونعناع',
    'basil-lemonade-juice': 'عصير ليمونادا بالريحان',
    'lemon-mint-juice': 'عصير ليمون ونعناع',
    'lemonade-juice': 'عصير ليمونادا',
    'pomegranate-juice': 'عصير رمان',
    'mango-basil-juice': 'عصير مانجو بالريحان',
    'forest-mojito': 'موهيتو الغابة',
    'mango-mojito': 'موهيتو مانجو',
    'pink-lemonade': 'ليمونادا وردية',
    'red-sea-redbull': 'ريد بول البحر الأحمر',
    'maldives-redbull': 'ريد بول المالديف',
    'ice-tea-peach': 'شاي مثلج خوخ',
    'iced-tea-mango': 'شاي مثلج مانجو',
    'iced-tea-sugar-free': 'شاي مثلج خالي السكر',
    'iced-tea-strawberry': 'شاي مثلج فراولة',
    'iced-tea-grenadine': 'شاي مثلج غرنادين',
    'ice-tea-forest': 'شاي مثلج الغابة',
    'ice-tea-passion-fruit': 'شاي مثلج فاكهة العاطفة',
    'black-tea': 'شاي أسود',
    'matcha': 'ماتشا',
    'special-tea': 'شاي خاص',
    'green-tea': 'شاي أخضر',
    'chai-latte-vanilla': 'تشاي لاتيه فانيلا',
    'chai-latte-spiced': 'تشاي لاتيه متبل',
    'hot-chocolate': 'شوكولاتة ساخنة',
    'coca-cola-zero': 'كوكا كولا زيرو',
    'redbull-sugar-free': 'ريد بول خالي السكر',
    'sprite-zero': 'سبرايت زيرو',
    'perrier': 'بيريه',
    'mineral-water': 'مياه معدنية',
    
    // Product Names - Food (Arabic - unique keys)
    'eggs-of-your-choice-ar': 'بيض على اختيارك',
    'french-toast-ar': 'توست فرنسي',
    'pancakes-ar': 'بان كيك',
    'margherita-pizza-ar': 'بيتزا مارغريتا',
    'pepperoni-pizza-ar': 'بيتزا ببروني',
    'quattro-stagioni-ar': 'كواترو ستاجيوني',
    'chicken-wings-ar': 'أجنحة دجاج',
    'mozzarella-sticks-ar': 'أصابع موزاريلا',
    'mexican-nachos-ar': 'ناتشوز مكسيكي',
    'dynamite-shrimp-ar': 'روبيان ديناميت',
    'chicken-dynamite-ar': 'دجاج ديناميت',
    'san-sebastian-cake-ar': 'كيك سان سيباستيان',
    'tiramisu-cake-ar': 'كيك تيراميسو',
    'cheesecake-ar': 'تشيز كيك',
    'kenafa-naama-ar': 'كنافة ناعمة',
    'club-sandwich-ar': 'ساندويتش كلوب',
    'chicken-sandwich-ar': 'ساندويتش دجاج',
    'grilled-cheese-ar': 'جبن مشوي',
    'spaghetti-carbonara-ar': 'سباغيتي كاربونارا',
    'fettuccine-alfredo-ar': 'فيتوتشيني ألفريدو',
    'risotto-mushroom-ar': 'ريزوتو فطر',
    'caesar-salad-ar': 'سلطة قيصر',
    'greek-salad-ar': 'سلطة يونانية',
    'quinoa-salad-ar': 'سلطة كينوا',
    'mushroom-soup-ar': 'شوربة فطر',
    'tomato-soup': 'شوربة طماطم',
    'chicken-noodle-soup': 'شوربة دجاج بالشعيرية',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    // Save language to localStorage and update document direction
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};