import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Header & Navigation
    'menu': 'MENU',
    'home': 'HOME',
    'back': 'BACK',
    'beverages': 'BEVERAGES',
    'food': 'FOOD',
    'shisha': 'SHISHA',
    'signatures': 'SIGNATURES',
    
    // Common UI
    'description': 'DESCRIPTION',
    'price': 'PRICE',
    'category': 'CATEGORY',
    'related-products': 'RELATED PRODUCTS',
    'drinks-menu': 'DRINKS MENU',
    'food-menu': 'FOOD MENU',
    'shisha-menu': 'SHISHA MENU',
    'welcome': 'Welcome to The Oak Cafe',
    'premium-experience': 'Premium Middle Eastern Experience',
    'oak-cafe': 'The Oak Cafe',
    
    // Categories
    'hot-drinks': 'HOT DRINKS',
    'category-hot-drinks': 'Hot Drinks',
    'cold-coffee': 'COLD COFFEE',
    'category-cold-coffee': 'Cold Coffee',
    'fresh-juice': 'FRESH JUICE',
    'category-fresh-juice': 'Fresh Juice',
    'soft-drinks': 'SOFT DRINKS',
    'category-soft-drinks': 'Soft Drinks',
    'frappe': 'FRAPPE',
    'category-frappe': 'Frappe',
    'milkshake': 'MILKSHAKE',
    'category-milkshake': 'Milkshake',
    'smoothies': 'SMOOTHIES',
    'category-smoothies': 'Smoothies',
    'mojito': 'MOJITO',
    'category-mojito': 'Mojito',
    'iced-tea': 'ICED TEA',
    'category-iced-tea': 'Iced Tea',
    'breakfast': 'BREAKFAST',
    'category-breakfast': 'Breakfast',
    'pizza': 'PIZZA',
    'category-pizza': 'Pizza',
    'sandwiches': 'SANDWICHES',
    'category-sandwiches': 'Sandwiches',
    'italian': 'ITALIAN',
    'category-italian': 'Italian',
    'main-course': 'MAIN COURSE',
    'category-main-course': 'Main Course',
    'appetizers': 'APPETIZERS',
    'category-appetizers': 'Appetizers',
    'salads': 'SALADS',
    'category-salads': 'Salads',
    'soup': 'SOUP',
    'category-soup': 'Soup',
    'desserts': 'DESSERTS',
    'category-desserts': 'Desserts',
    'regular': 'REGULAR SHISHA',
    'category-regular': 'Regular Shisha',
    'premium': 'PREMIUM SHISHA',
    'category-premium': 'Premium Shisha',
    'special': 'SPECIAL SHISHA',
    'category-special': 'Special Shisha',
    
    // Product Names
    'red-eye': 'Red Eye',
    'v60': 'V60',
    'chemex': 'Chemex',
    'flat-white': 'Flat White',
    'espresso-macchiato': 'Espresso Macchiato',
    'marshmallow-hot-chocolate': 'Marshmallow Hot Chocolate',
    'turkish-coffee-single': 'Turkish Coffee Single',
    'double-espresso': 'Double Espresso',
    'cappuccino': 'Cappuccino',
    'cortado': 'Cortado',
    'latte': 'Latte',
    'americano': 'Americano',
    'turkish-coffee-double': 'Turkish Coffee Double',
    'oak-seasonal-juice': 'Oak Seasonal Juice',
    'pomegranate': 'Pomegranate',
    'mango-mint': 'Mango Mint',
    'orange-juice': 'Orange Juice',
    'coca-cola': 'Coca Cola',
    'sprite': 'Sprite',
    'red-bull': 'Red Bull',
    'eggs-of-your-choice': 'Eggs of Your Choice',
    'halloumi-croissant': 'Halloumi Croissant',
    'tuna-sandwich': 'Tuna Sandwich',
    'manakish-labneh-rocca': 'Manakish Labneh Rocca',
    'turkey-omelette-croissant': 'Turkey Omelette Croissant',
    'zaatar-pomegranate': 'Zaatar Pomegranate',
    'avocado-omelette': 'Avocado Omelette',
    'manakish-falafel': 'Manakish Falafel',
    'manakish-nabulsi-cheese': 'Manakish Nabulsi Cheese',
    'manakish-zaatar-vegetables': 'Manakish Zaatar Vegetables',
    'marshmallow-chocolate': 'Marshmallow Chocolate',
    'turkey-croissant': 'Turkey Croissant',
    'manakish-mix-cheese': 'Manakish Mix Cheese',
    'manakish-molasses-tahini': 'Manakish Molasses Tahini',
    'chicken-bbq-pizza': 'Chicken BBQ Pizza',
    'pizza-margherita': 'Pizza Margherita',
    'pepperoni-pizza': 'Pepperoni Pizza',
    'mix-formaggio': 'Mix Formaggio',
    'pizza-chicken-alfredo': 'Pizza Chicken Alfredo',
    'calzone-pizza': 'Calzone Pizza',
    'pepperoni': 'Pepperoni',
    'oak-steak': 'Oak Steak',
    'salmon-grill': 'Salmon Grill',
    'beef-steak': 'Beef Steak',
    'chicken-mushroom': 'Chicken Mushroom',
    'club-sandwich': 'Club Sandwich',
    'chicken-sandwich': 'Chicken Sandwich',
    'grilled-cheese': 'Grilled Cheese',
    'oak-beef-burger': 'Oak Beef Burger',
    'crispy-chicken-burger': 'Crispy Chicken Burger',
    'shawarma-meat': 'Shawarma Meat',
    'oak-sandwich': 'Oak Sandwich',
    'fettuccine-alfredo': 'Fettuccine Alfredo',
    'spaghetti-bolognese': 'Spaghetti Bolognese',
    'penne-arrabbiata': 'Penne Arrabbiata',
    'seafood-pasta': 'Seafood Pasta',
    'pesto-pasta': 'Pesto Pasta',
    'lasagna': 'Lasagna',
    'rose-pasta': 'Rose Pasta',
    'mac-and-cheese': 'Mac and Cheese',
    'caesar-salad': 'Caesar Salad',
    'greek-salad': 'Greek Salad',
    'fattoush-salad': 'Fattoush Salad',
    'tabbouleh-salad': 'Tabbouleh Salad',
    'quinoa-salad': 'Quinoa Salad',
    'chicken-wings': 'Chicken Wings',
    'mozzarella-sticks': 'Mozzarella Sticks',
    'onion-rings': 'Onion Rings',
    'dynamite-shrimp': 'Dynamite Shrimp',
    'chicken-dynamite': 'Chicken Dynamite',
    'mexican-nachos': 'Mexican Nachos',
    'hash-browns': 'Hash Browns',
    'french-toast': 'French Toast',
    'pancakes': 'Pancakes',
    'waffles': 'Waffles',
    'chocolate-milkshake': 'Chocolate Milkshake',
    'vanilla-milkshake': 'Vanilla Milkshake',
    'strawberry-milkshake': 'Strawberry Milkshake',
    'caramel-frappe': 'Caramel Frappe',
    'vanilla-frappe': 'Vanilla Frappe',
    'chocolate-frappe': 'Chocolate Frappe',
    'mango-smoothie': 'Mango Smoothie',
    'berry-smoothie': 'Berry Smoothie',
    'banana-smoothie': 'Banana Smoothie',
    'lemon-mojito': 'Lemon Mojito',
    'mint-mojito': 'Mint Mojito',
    'watermelon-juice': 'Watermelon Juice',
    'apple-juice': 'Apple Juice',
    'carrot-juice': 'Carrot Juice',
    'green-tea': 'Green Tea',
    'black-tea': 'Black Tea',
    'chamomile-tea': 'Chamomile Tea',
    'earl-grey-tea': 'Earl Grey Tea',
    'tiramisu-cake': 'Tiramisu Cake',
    'cheesecake': 'Cheesecake',
    'chocolate-cake': 'Chocolate Cake',
    'san-sebastian-cake': 'San Sebastian Cake',
    'v60-chemex': 'V60 / CHEMEX',
    'caramel-macchiato': 'Caramel Macchiato',
    'lungo': 'Lungo',
    'white-coffee': 'White Coffee',
    'sandy-chocolate': 'Sandy Chocolate',
    'filter-coffee': 'Filter Coffee',
    'white-mocha': 'White Mocha',
    'chili-chocolate': 'Chili Chocolate',
    'spanish-latte': 'Spanish Latte',
    'dark-mocha': 'Dark Mocha',
    'iced-caramel-macchiato': 'Iced Caramel Macchiato',
    'iced-dark-mocha': 'Iced Dark Mocha',
    'iced-flat-white': 'Iced Flat White',
    'iced-white-mocha': 'Iced White Mocha',
    'cold-brew': 'Cold Brew',
    'iced-americano': 'Iced Americano',
    'iced-latte': 'Iced Latte',
    'iced-spanish-latte': 'Iced Spanish Latte',
    'hazelnut-frappe': 'Hazelnut Frappe',
    'white-fruit-frappe': 'White Fruit Frappe',
    'white-chocolate-frappe': 'White Chocolate Frappe',
    'coffee-frappe': 'Coffee Frappe',
    'arabia-milkshake': 'Arabia Milkshake',
    'lemon-milkshake': 'Lemon Milkshake',
    'caramel-milkshake': 'Caramel Milkshake',
    'mango-milkshake': 'Mango Milkshake',
    'mix-berries-smoothie': 'Mix Berries Smoothie',
    'lemonade-smoothie': 'Lemonade Smoothie',
    'mango-passionfruit-smoothie': 'Mango and Passionfruit Smoothie',
    'lemon-mint-smoothie': 'Lemon with Mint Smoothie',
    'basil-lemonade-smoothie': 'Basil Lemonade Smoothie',
    'orange-smoothie': 'Orange Smoothie',
    'mango-mint-juice': 'Mango Mint Juice',
    'basil-lemonade-juice': 'Basil Lemonade Juice',
    'lemon-mint-juice': 'Lemon with Mint Juice',
    'lemonade-juice': 'Lemonade Juice',
    'pomegranate-juice': 'Pomegranate Juice',
    'mango-basil-juice': 'Mango Basil Juice',
    'forest-mojito': 'Forest Mojito',
    'mango-mojito': 'Mango Mojito',
    'pink-lemonade': 'Pink Lemonade',
    'red-sea-redbull': 'Red Sea Red Bull',
    'maldives-redbull': 'Maldives Red Bull',
    'ice-tea-peach': 'Ice Tea Peach',
    'iced-tea-mango': 'Iced Tea Mango',
    'iced-tea-sugar-free': 'Iced Tea Sugar Free',
    'iced-tea-strawberry': 'Iced Tea Strawberry',
    'iced-tea-grenadine': 'Iced Tea Grenadine',
    'classic-iced-tea': 'Classic Iced Tea',
    'fanta': 'Fanta',
    'mix-platter': 'Mix Platter',
    'kenafa-naama': 'Kenafa Naama',
    'ice-cream-vanilla': 'Vanilla Ice Cream',
    'ice-cream-chocolate': 'Chocolate Ice Cream',
    'ice-cream-strawberry': 'Strawberry Ice Cream',
    'tiramisu': 'Tiramisu',
    'oak-beef-burger': 'OAK Beef Burger',
    'oak-sandwich': 'The Oak Sandwich',
    'shawarma-meat': 'Shawarma Meat',
    'crispy-chicken-burger': 'Crispy Chicken Burger',
    'mix-formaggio': 'Mix Formaggio',
    'pizza-chicken-alfredo': 'Pizza Chicken Alfredo',
    'calzone-pizza': 'Calzone Pizza',
    'pepperoni': 'Pepperoni',
    'oak-steak': 'The Oak Steak',
    'salmon-grill': 'Salmon Grill',
    'beef-steak': 'Beef Steak',
    'chicken-mushroom': 'Chicken Mushroom',
    'mexican-nachos': 'Mexican Nachos',
    'chicken-dynamite': 'Chicken Dynamite',
    'eggs-of-your-choice': 'Eggs of Your Choice',
    'turkey-omelette-croissant': 'Turkey Omelette Croissant',
    'avocado-omelette': 'Avocado Omelette',
    'turkey-croissant': 'Turkey Croissant',
    'classic-mojito': 'Classic Mojito',
    'strawberry-mojito': 'Strawberry Mojito',
    'passion-fruit-mojito': 'Passion Fruit Mojito',
    'ice-tea-forest': 'Ice Tea Forest',
    'ice-tea-passion-fruit': 'Ice Tea Passion Fruit',
    'coca-cola': 'Coca Cola',
    'coca-cola-zero': 'Coca Cola Zero',
    'sprite': 'Sprite',
    'sprite-zero': 'Sprite Zero',
    'mineral-water': 'Mineral Water',
    'perrier': 'Perrier',
    'red-bull': 'Red Bull',
    'redbull-sugar-free': 'Red Bull Sugar Free',
    'hot-chocolate': 'Hot Chocolate',
    'green-tea': 'Green Tea',
    'black-tea': 'Black Tea',
    'chai-latte-spiced': 'Chai Latte Spiced',
    'chai-latte-vanilla': 'Chai Latte Vanilla',
    'special-tea': 'Special Tea',
    'matcha': 'Matcha',
    'vanilla-frappe': 'Vanilla Frappe',
    'chef-salad': 'Chef Salad',
    'greek-salad': 'Greek Salad',
    'caesar-salad': 'Caesar Salad',
    'smoked-salmon-salad': 'Smoked Salmon Salad',
    'mushroom-soup': 'Mushroom Soup',
    'seafood-soup': 'Seafood Soup',
    'corn-soup': 'Corn Soup',
    
    // Product Descriptions
    'red-eye-desc': 'Strong coffee with espresso shot',
    'v60-desc': 'Specialty pour-over coffee',
    'flat-white-desc': 'Smooth espresso with steamed milk and light foam',
    'espresso-macchiato-desc': 'Espresso with steamed milk foam',
    'marshmallow-hot-chocolate-desc': 'Rich hot chocolate with marshmallows',
    'turkish-coffee-single-desc': 'Traditional Turkish coffee prepared in authentic copper pot',
    'double-espresso-desc': 'Double shot of rich espresso for the ultimate coffee experience',
    'eggs-of-your-choice-desc': 'Fresh eggs prepared exactly as you like them',
    'halloumi-croissant-desc': 'Buttery croissant filled with grilled halloumi cheese',
    'tuna-sandwich-desc': 'Fresh tuna salad sandwich with crisp vegetables',
    'manakish-labneh-rocca-desc': 'Traditional Middle Eastern bread with labneh and rocca leaves',
    'zaatar-pomegranate-desc': 'Traditional zaatar bread with pomegranate molasses',
    'manakish-falafel-desc': 'Traditional falafel manakish',
    'manakish-nabulsi-cheese-desc': 'Authentic Nabulsi cheese manakish',
    'manakish-zaatar-vegetables-desc': 'Zaatar manakish with fresh vegetables',
    'marshmallow-chocolate-desc': 'Rich hot chocolate with marshmallows',

    'manakish-mix-cheese-desc': 'Delicious mixed cheese manakish',
    'manakish-molasses-tahini-desc': 'Traditional molasses and tahini manakish',
    'chicken-bbq-pizza-desc': 'BBQ chicken pizza with tender chicken pieces and BBQ sauce',
    'pizza-margherita-desc': 'Classic Italian pizza with fresh mozzarella, tomatoes, and basil',
    'pepperoni-pizza-desc': 'Classic pepperoni pizza with spicy pepperoni slices',
    'mix-formaggio-desc': 'Mixed cheese pizza with four different types of cheese',
    'pizza-chicken-alfredo-desc': 'Creamy Alfredo pizza with grilled chicken',
    'calzone-pizza-desc': 'Traditional Italian folded pizza with cheese and fillings',
    'pepperoni-desc': 'Classic pepperoni pizza with spicy pepperoni slices',
    'oak-steak-desc': 'Premium beef steak grilled to perfection',
    'salmon-grill-desc': 'Fresh grilled salmon with herbs and lemon',
    'beef-steak-desc': 'Tender beef steak cooked to your preference',
    'chicken-mushroom-desc': 'Grilled chicken breast with mushroom sauce',
    'club-sandwich-desc': 'Classic club sandwich with turkey, bacon, lettuce, and tomato',
    'chicken-sandwich-desc': 'Grilled chicken sandwich with fresh vegetables and special sauce',
    'grilled-cheese-desc': 'Golden grilled cheese sandwich with melted cheese and crispy bread',
    'oak-beef-burger-desc': 'Premium beef burger with fresh vegetables and our signature sauce',
    'crispy-chicken-burger-desc': 'Crispy fried chicken burger with fresh toppings',
    'shawarma-meat-desc': 'Traditional Middle Eastern shawarma with seasoned meat',
    'oak-sandwich-desc': 'Our signature sandwich with premium ingredients',
    'fettuccine-alfredo-desc': 'Classic Italian pasta with creamy Alfredo sauce',
    'spaghetti-bolognese-desc': 'Traditional spaghetti with rich meat sauce',
    'penne-arrabbiata-desc': 'Spicy pasta with tomato sauce and chili',
    'seafood-pasta-desc': 'Fresh pasta with mixed seafood in tomato sauce',
    'pesto-pasta-desc': 'Pasta with fresh basil pesto sauce',
    'lasagna-desc': 'Traditional layered pasta with meat sauce and cheese',
    'rose-pasta-desc': 'Pasta with creamy tomato rose sauce',
    'mac-and-cheese-desc': 'Classic macaroni with creamy cheese sauce',

    'fattoush-salad-desc': 'Middle Eastern salad with mixed vegetables and crispy bread',
    'tabbouleh-salad-desc': 'Fresh parsley salad with tomatoes and bulgur',
    'quinoa-salad-desc': 'Healthy quinoa salad with fresh vegetables',
    'chicken-wings-desc': 'Crispy chicken wings with special sauce',
    'mozzarella-sticks-desc': 'Golden fried mozzarella cheese sticks',
    'onion-rings-desc': 'Crispy battered onion rings',
    'dynamite-shrimp-desc': 'Spicy shrimp with dynamite sauce',
    'chicken-dynamite-desc': 'Crispy chicken with spicy dynamite sauce',
    'mexican-nachos-desc': 'Tortilla chips with cheese, jalapeños, and toppings',
    'hash-browns-desc': 'Golden crispy potato hash browns',
    'french-toast-desc': 'Classic French toast with syrup',
    'pancakes-desc': 'Fluffy pancakes with syrup and butter',
    'waffles-desc': 'Golden waffles with syrup',
    'chocolate-milkshake-desc': 'Rich chocolate milkshake',
    'vanilla-milkshake-desc': 'Creamy vanilla milkshake',
    'strawberry-milkshake-desc': 'Fresh strawberry milkshake',
    'caramel-frappe-desc': 'Iced coffee with caramel flavor',
    'vanilla-frappe-desc': 'Iced coffee with vanilla flavor',
    'chocolate-frappe-desc': 'Iced coffee with chocolate flavor',
    'mango-smoothie-desc': 'Fresh mango smoothie',
    'berry-smoothie-desc': 'Mixed berry smoothie',
    'banana-smoothie-desc': 'Creamy banana smoothie',
    'lemon-mojito-desc': 'Refreshing lemon mojito',
    'mint-mojito-desc': 'Fresh mint mojito',
    'watermelon-juice-desc': 'Fresh watermelon juice',
    'apple-juice-desc': 'Fresh apple juice',
    'carrot-juice-desc': 'Fresh carrot juice',
    'green-tea-desc': 'Traditional green tea',
    'black-tea-desc': 'Classic black tea',
    'chamomile-tea-desc': 'Relaxing chamomile tea',
    'earl-grey-tea-desc': 'Traditional Earl Grey tea',
    'tiramisu-cake-desc': 'Classic Italian dessert with coffee and mascarpone',
    'cheesecake-desc': 'Rich and creamy cheesecake',
    'chocolate-cake-desc': 'Decadent chocolate cake',
    'san-sebastian-cake-desc': 'Spanish burnt cheesecake',
    'v60-chemex-desc': 'Specialty V60 pour-over or Chemex coffee brewing methods',
    'caramel-macchiato-desc': 'Espresso with caramel flavoring and steamed milk',
    'lungo-desc': 'Long espresso shot with more water for lighter taste',
    'white-coffee-desc': 'Traditional white coffee with condensed milk',
    'sandy-chocolate-desc': 'Rich chocolate drink with a unique sandy texture',
    'filter-coffee-desc': 'Classic drip coffee made with precision brewing',
    'white-mocha-desc': 'Creamy white chocolate mocha with espresso',
    'chili-chocolate-desc': 'Spicy chocolate drink with a hint of chili',
    'spanish-latte-desc': 'Spanish-style latte with condensed milk',
    'dark-mocha-desc': 'Rich dark chocolate mocha with espresso',
    'iced-caramel-macchiato-desc': 'Chilled caramel macchiato over ice',
    'iced-dark-mocha-desc': 'Cold dark chocolate mocha over ice',
    'iced-flat-white-desc': 'Chilled flat white coffee over ice',
    'iced-white-mocha-desc': 'Cold white chocolate mocha over ice',
    'cold-brew-desc': 'Smooth cold-brewed coffee served chilled',
    'iced-americano-desc': 'Classic americano served over ice',
    'iced-latte-desc': 'Creamy iced latte with steamed milk',
    'iced-spanish-latte-desc': 'Chilled Spanish latte with condensed milk',
    'hazelnut-frappe-desc': 'Blended iced coffee with hazelnut flavor',
    'white-fruit-frappe-desc': 'Fruity white chocolate frappe blend',
    'white-chocolate-frappe-desc': 'Creamy white chocolate blended with ice',
    'coffee-frappe-desc': 'Classic coffee frappe blended with ice',
    'arabia-milkshake-desc': 'Traditional Arabic-style milkshake',
    'lemon-milkshake-desc': 'Tangy lemon-flavored milkshake',
    'caramel-milkshake-desc': 'Sweet caramel milkshake',
    'mango-milkshake-desc': 'Tropical mango milkshake',
    'mix-berries-smoothie-desc': 'Antioxidant-rich mixed berry smoothie',
    'lemonade-smoothie-desc': 'Refreshing lemonade smoothie blend',
    'mango-passionfruit-smoothie-desc': 'Tropical mango and passionfruit blend',
    'lemon-mint-smoothie-desc': 'Refreshing lemon and mint smoothie',
    'basil-lemonade-smoothie-desc': 'Unique basil-infused lemonade smoothie',
    'orange-smoothie-desc': 'Fresh orange smoothie packed with vitamin C',
    'mango-mint-juice-desc': 'Fresh mango juice with mint leaves',
    'basil-lemonade-juice-desc': 'Aromatic basil lemonade juice',
    'lemon-mint-juice-desc': 'Refreshing lemon juice with fresh mint',
    'lemonade-juice-desc': 'Classic fresh lemonade',
    'pomegranate-juice-desc': 'Antioxidant-rich pomegranate juice',
    'mango-basil-juice-desc': 'Exotic mango juice with fresh basil',
    'forest-mojito-desc': 'Herbal forest-inspired mojito mocktail',
    'mango-mojito-desc': 'Tropical mango mojito mocktail',
    'pink-lemonade-desc': 'Sweet pink lemonade with berry flavor',
    'red-sea-redbull-desc': 'Red Bull energy drink with red sea flavor',
    'maldives-redbull-desc': 'Tropical Maldives-inspired Red Bull',
    'ice-tea-peach-desc': 'Refreshing peach iced tea',
    'iced-tea-mango-desc': 'Tropical mango iced tea',
    'iced-tea-sugar-free-desc': 'Sugar-free iced tea option',
    'iced-tea-strawberry-desc': 'Sweet strawberry iced tea',
    'iced-tea-grenadine-desc': 'Iced tea with grenadine syrup',
    'classic-iced-tea-desc': 'Traditional iced tea served chilled',
    'fanta-desc': 'Classic orange-flavored soft drink',
    'mix-platter-desc': 'Assorted appetizer platter with various selections',
    'kenafa-naama-desc': 'Traditional Middle Eastern dessert with cheese and syrup',
    'ice-cream-vanilla-desc': 'Classic vanilla ice cream',
    'ice-cream-chocolate-desc': 'Rich chocolate ice cream',
    'ice-cream-strawberry-desc': 'Fresh strawberry ice cream',
    'tiramisu-desc': 'Classic Italian dessert with coffee and mascarpone',

    'oak-sandwich-desc': 'The Oak special sandwich with unique combination of flavors',
    'shawarma-meat-desc': 'Traditional Middle Eastern meat shawarma',
    'crispy-chicken-burger-desc': 'Crispy fried chicken burger with fresh toppings',
    'mix-formaggio-desc': 'Pizza with a variety of premium cheeses',
    'pizza-chicken-alfredo-desc': 'Pizza topped with chicken and creamy Alfredo sauce',
    'calzone-pizza-desc': 'Folded pizza filled with cheese and toppings',



    'turkey-omelette-croissant-desc': 'Flaky croissant with turkey and omelette',
    'avocado-omelette-desc': 'Healthy omelette with fresh avocado',
    'turkey-croissant-desc': 'Croissant filled with premium turkey slices',
    'classic-mojito-desc': 'Traditional mojito with fresh mint',
    'strawberry-mojito-desc': 'Refreshing mojito with strawberry flavor',
    'passion-fruit-mojito-desc': 'Exotic mojito with passion fruit',
    'ice-tea-forest-desc': 'Forest-flavored iced tea blend',
    'ice-tea-passion-fruit-desc': 'Passion fruit iced tea',
    'coca-cola-desc': 'Classic Coca Cola soft drink',
    'coca-cola-zero-desc': 'Sugar-free Coca Cola',
    'sprite-desc': 'Lemon-lime flavored soft drink',
    'sprite-zero-desc': 'Sugar-free lemon-lime soft drink',
    'mineral-water-desc': 'Pure mineral water',
    'perrier-desc': 'Sparkling natural mineral water',
    'red-bull-desc': 'Energy drink with caffeine and taurine',
    'redbull-sugar-free-desc': 'Sugar-free energy drink',
    'hot-chocolate-desc': 'Rich and creamy hot chocolate',
    'green-tea-desc': 'Antioxidant-rich green tea',
    'black-tea-desc': 'Classic black tea',
    'chai-latte-spiced-desc': 'Spiced chai latte with aromatic spices',
    'chai-latte-vanilla-desc': 'Vanilla-flavored chai latte',
    'special-tea-desc': 'Our signature special tea blend',
    'matcha-desc': 'Premium Japanese matcha green tea',
    'vanilla-frappe-desc': 'Creamy vanilla frappe blended with ice',
    'chef-salad-desc': 'Mixed greens with chef\'s special ingredients and dressing',
    'greek-salad-desc': 'Traditional Greek salad with feta cheese and olives',
    'caesar-salad-desc': 'Classic Caesar salad with romaine lettuce and parmesan',
    'smoked-salmon-salad-desc': 'Fresh salad topped with premium smoked salmon',
    'mushroom-soup-desc': 'Creamy mushroom soup with fresh herbs',
    'seafood-soup-desc': 'Rich seafood soup with mixed catches of the day',
    'corn-soup-desc': 'Sweet corn soup with a creamy base',
    'oak-seasonal-juice-desc': 'Our signature seasonal blend of the finest available fruits',
  },
  ar: {
    // Header & Navigation
    'menu': 'القائمة',
    'home': 'الرئيسية',
    'back': 'رجوع',
    'beverages': 'المشروبات',
    'food': 'الطعام',
    'shisha': 'الشيشة',
    'signatures': 'التوقيعات',
    
    // Common UI
    'description': 'الوصف',
    'price': 'السعر',
    'category': 'الفئة',
    'related-products': 'منتجات ذات صلة',
    'drinks-menu': 'قائمة المشروبات',
    'food-menu': 'قائمة الطعام',
    'shisha-menu': 'قائمة الشيشة',
    'welcome': 'مرحباً بكم في مقهى أوك',
    'premium-experience': 'تجربة شرق أوسطية مميزة',
    'oak-cafe': 'مقهى أوك',
    
    // Categories
    'hot-drinks': 'المشروبات الساخنة',
    'category-hot-drinks': 'المشروبات الساخنة',
    'cold-coffee': 'القهوة الباردة',
    'category-cold-coffee': 'القهوة الباردة',
    'fresh-juice': 'العصائر الطازجة',
    'category-fresh-juice': 'العصائر الطازجة',
    'soft-drinks': 'المشروبات الغازية',
    'category-soft-drinks': 'المشروبات الغازية',
    'frappe': 'فرابيه',
    'category-frappe': 'فرابيه',
    'milkshake': 'ميلك شيك',
    'category-milkshake': 'ميلك شيك',
    'smoothies': 'سموذي',
    'category-smoothies': 'سموذي',
    'mojito': 'موهيتو',
    'category-mojito': 'موهيتو',
    'iced-tea': 'الشاي المثلج',
    'category-iced-tea': 'الشاي المثلج',
    'breakfast': 'الإفطار',
    'category-breakfast': 'الإفطار',
    'pizza': 'البيتزا',
    'category-pizza': 'البيتزا',
    'sandwiches': 'الساندويتشات',
    'category-sandwiches': 'الساندويتشات',
    'italian': 'الإيطالي',
    'category-italian': 'الإيطالي',
    'main-course': 'الأطباق الرئيسية',
    'category-main-course': 'الأطباق الرئيسية',
    'appetizers': 'المقبلات',
    'category-appetizers': 'المقبلات',
    'salads': 'السلطات',
    'category-salads': 'السلطات',
    'soup': 'الشوربة',
    'category-soup': 'الشوربة',
    'desserts': 'الحلويات',
    'category-desserts': 'الحلويات',
    'regular': 'الشيشة العادية',
    'category-regular': 'الشيشة العادية',
    'premium': 'الشيشة المميزة',
    'category-premium': 'الشيشة المميزة',
    'special': 'الشيشة الخاصة',
    'category-special': 'الشيشة الخاصة',
    
    // Product Names
    'red-eye': 'قهوة ريد آي',
    'v60': 'قهوة مختصة في ٦٠',
    'chemex': 'قهوة كيمكس',
    'flat-white': 'قهوة فلات وايت',
    'espresso-macchiato': 'إسبريسو ماكياتو',
    'marshmallow-hot-chocolate': 'شوكولاتة ساخنة بالمارشملو',
    'turkish-coffee-single': 'قهوة تركية مفردة',
    'double-espresso': 'إسبريسو مزدوج',
    'cappuccino': 'كابتشينو',
    'cortado': 'كورتادو',
    'latte': 'لاتيه',
    'americano': 'أمريكانو',
    'turkish-coffee-double': 'قهوة تركية مزدوجة',
    'oak-seasonal-juice': 'عصير أوك الموسمي الطازج',
    'pomegranate': 'رمان',
    'mango-mint': 'مانجو بالنعناع',
    'orange-juice': 'عصير برتقال',
    'coca-cola': 'كوكا كولا',
    'sprite': 'سبرايت',
    'red-bull': 'ريد بول',
    'eggs-of-your-choice': 'بيض حسب الطلب',
    'halloumi-croissant': 'كرواسان حلوم',
    'tuna-sandwich': 'ساندويش تونة',
    'manakish-labneh-rocca': 'مناقيش لبنة وجرجير',
    'turkey-omelette-croissant': 'كرواسان أومليت ديك رومي',
    'zaatar-pomegranate': 'زعتر ودبس رمان',
    'avocado-omelette': 'أومليت أفوكادو',
    'manakish-falafel': 'مناقيش فلافل',
    'manakish-nabulsi-cheese': 'مناقيش جبن نابلسي',
    'manakish-zaatar-vegetables': 'مناقيش زعتر وخضار',
    'marshmallow-chocolate': 'شوكولاتة مارشمالو',
    'turkey-croissant': 'كرواسان تركي',
    'manakish-mix-cheese': 'مناقيش جبن مشكل',
    'manakish-molasses-tahini': 'مناقيش دبس وطحينة',
    'chicken-bbq-pizza': 'بيتزا دجاج باربكيو',
    'pizza-margherita': 'بيتزا مارغريتا',
    'pepperoni-pizza': 'بيتزا بيبروني',
    'mix-formaggio': 'ميكس فورماجيو',
    'pizza-chicken-alfredo': 'بيتزا دجاج ألفريدو',
    'calzone-pizza': 'كالزونيه بيتزا',
    'pepperoni': 'بيبروني',
    'oak-steak': 'ستيك الأوك',
    'salmon-grill': 'سلمون مشوي',
    'beef-steak': 'ستيك لحم بقري',
    'chicken-mushroom': 'دجاج بالفطر',
    'club-sandwich': 'ساندويش كلوب',
    'chicken-sandwich': 'ساندويش دجاج',
    'grilled-cheese': 'جبن مشوي',
    'oak-beef-burger': 'برغر أوك اللحم البقري',
    'crispy-chicken-burger': 'برغر دجاج مقرمش',
    'shawarma-meat': 'شاورما لحمة',
    'oak-sandwich': 'ساندويش أوك',
    'fettuccine-alfredo': 'فيتوتشيني ألفريدو',
    'spaghetti-bolognese': 'سباغيتي بولونيز',
    'penne-arrabbiata': 'بيني أرابياتا',
    'seafood-pasta': 'باستا ثمار البحر',
    'pesto-pasta': 'باستا بيستو',
    'lasagna': 'لازانيا',
    'rose-pasta': 'باستا الوردة',
    'mac-and-cheese': 'ماك أند تشيز',
    'caesar-salad': 'سلطة قيصر',
    'greek-salad': 'سلطة يونانية',
    'fattoush-salad': 'سلطة فتوش',
    'tabbouleh-salad': 'سلطة تبولة',
    'quinoa-salad': 'سلطة كينوا',
    'chicken-wings': 'أجنحة دجاج',
    'mozzarella-sticks': 'أصابع موزاريلا',
    'onion-rings': 'حلقات البصل',
    'dynamite-shrimp': 'جمبري ديناميت',
    'chicken-dynamite': 'دجاج ديناميت',
    'mexican-nachos': 'ناتشوز مكسيكي',
    'hash-browns': 'هاش براون',
    'french-toast': 'توست فرنسي',
    'pancakes': 'بان كيك',
    'waffles': 'وافل',
    'chocolate-milkshake': 'ميلك شيك شوكولاتة',
    'vanilla-milkshake': 'ميلك شيك فانيليا',
    'strawberry-milkshake': 'ميلك شيك فراولة',
    'caramel-frappe': 'فرابيه كراميل',
    'vanilla-frappe': 'فرابيه فانيليا',
    'chocolate-frappe': 'فرابيه شوكولاتة',
    'mango-smoothie': 'سموذي مانجو',
    'berry-smoothie': 'سموذي توت',
    'banana-smoothie': 'سموذي موز',
    'lemon-mojito': 'موهيتو ليمون',
    'mint-mojito': 'موهيتو نعناع',
    'watermelon-juice': 'عصير بطيخ',
    'apple-juice': 'عصير تفاح',
    'carrot-juice': 'عصير جزر',
    'green-tea': 'شاي أخضر',
    'black-tea': 'شاي أسود',
    'chamomile-tea': 'شاي بابونج',
    'earl-grey-tea': 'شاي إيرل جراي',
    'tiramisu-cake': 'كيك تيراميسو',
    'cheesecake': 'تشيز كيك',
    'chocolate-cake': 'كيك شوكولاتة',
    'san-sebastian-cake': 'كيك سان سيباستيان',
    'v60-chemex': 'في٦٠ / كيمكس',
    'caramel-macchiato': 'كراميل ماكياتو',
    'lungo': 'لونجو',
    'white-coffee': 'قهوة بيضاء',
    'sandy-chocolate': 'شوكولاتة رملية',
    'filter-coffee': 'قهوة مفلترة',
    'white-mocha': 'موكا بيضاء',
    'chili-chocolate': 'شوكولاتة حارة',
    'spanish-latte': 'لاتيه إسبانية',
    'dark-mocha': 'موكا داكنة',
    'iced-caramel-macchiato': 'كراميل ماكياتو مثلج',
    'iced-dark-mocha': 'موكا داكنة مثلجة',
    'iced-flat-white': 'فلات وايت مثلج',
    'iced-white-mocha': 'موكا بيضاء مثلجة',
    'cold-brew': 'قهوة باردة',
    'iced-americano': 'أمريكانو مثلج',
    'iced-latte': 'لاتيه مثلج',
    'iced-spanish-latte': 'لاتيه إسبانية مثلجة',
    'hazelnut-frappe': 'فرابيه بندق',
    'white-fruit-frappe': 'فرابيه فواكه بيضاء',
    'white-chocolate-frappe': 'فرابيه شوكولاتة بيضاء',
    'coffee-frappe': 'فرابيه قهوة',
    'arabia-milkshake': 'ميلك شيك عربي',
    'lemon-milkshake': 'ميلك شيك ليمون',
    'caramel-milkshake': 'ميلك شيك كراميل',
    'mango-milkshake': 'ميلك شيك مانجو',
    'mix-berries-smoothie': 'سموذي توت مشكل',
    'lemonade-smoothie': 'سموذي ليمونادة',
    'mango-passionfruit-smoothie': 'سموذي مانجو وباشن فروت',
    'lemon-mint-smoothie': 'سموذي ليمون ونعناع',
    'basil-lemonade-smoothie': 'سموذي ليمونادة بالريحان',
    'orange-smoothie': 'سموذي برتقال',
    'mango-mint-juice': 'عصير مانجو بالنعناع',
    'basil-lemonade-juice': 'عصير ليمونادة بالريحان',
    'lemon-mint-juice': 'عصير ليمون بالنعناع',
    'lemonade-juice': 'عصير ليمونادة',
    'pomegranate-juice': 'عصير رمان',
    'mango-basil-juice': 'عصير مانجو بالريحان',
    'forest-mojito': 'موهيتو الغابة',
    'mango-mojito': 'موهيتو مانجو',
    'pink-lemonade': 'ليمونادة وردية',
    'red-sea-redbull': 'ريد بول البحر الأحمر',
    'maldives-redbull': 'ريد بول المالديف',
    'ice-tea-peach': 'شاي مثلج بالخوخ',
    'iced-tea-mango': 'شاي مثلج بالمانجو',
    'iced-tea-sugar-free': 'شاي مثلج خالي من السكر',
    'iced-tea-strawberry': 'شاي مثلج بالفراولة',
    'iced-tea-grenadine': 'شاي مثلج بالجرانادين',
    'classic-iced-tea': 'شاي مثلج كلاسيكي',
    'fanta': 'فانتا',
    'mix-platter': 'طبق مشكل',
    'kenafa-naama': 'كنافة نعمة',
    'ice-cream-vanilla': 'آيس كريم فانيليا',
    'ice-cream-chocolate': 'آيس كريم شوكولاتة',
    'ice-cream-strawberry': 'آيس كريم فراولة',
    'tiramisu': 'تيراميسو',
    'oak-beef-burger': 'برجر أوك بيف',
    'oak-sandwich': 'ساندويش أوك',
    'shawarma-meat': 'شاورما لحم',
    'crispy-chicken-burger': 'برجر دجاج مقرمش',
    'mix-formaggio': 'ميكس فورماجيو',
    'pizza-chicken-alfredo': 'بيتزا دجاج ألفريدو',
    'calzone-pizza': 'بيتزا كالزوني',
    'pepperoni': 'بيبروني',
    'oak-steak': 'ستيك أوك',
    'salmon-grill': 'سلمون مشوي',
    'beef-steak': 'ستيك لحم',
    'chicken-mushroom': 'دجاج بالفطر',
    'mexican-nachos': 'ناتشوز مكسيكي',
    'chicken-dynamite': 'دجاج ديناميت',
    'eggs-of-your-choice': 'بيض حسب اختيارك',
    'turkey-omelette-croissant': 'كرواسون أومليت ديك رومي',
    'avocado-omelette': 'أومليت أفوكادو',
    'turkey-croissant': 'كرواسون ديك رومي',
    'classic-mojito': 'موهيتو كلاسيكي',
    'strawberry-mojito': 'موهيتو فراولة',
    'passion-fruit-mojito': 'موهيتو باشن فروت',
    'ice-tea-forest': 'شاي مثلج الغابة',
    'ice-tea-passion-fruit': 'شاي مثلج باشن فروت',
    'coca-cola': 'كوكا كولا',
    'coca-cola-zero': 'كوكا كولا زيرو',
    'sprite': 'سبرايت',
    'sprite-zero': 'سبرايت زيرو',
    'mineral-water': 'مياه معدنية',
    'perrier': 'بيريير',
    'red-bull': 'ريد بول',
    'redbull-sugar-free': 'ريد بول خالي من السكر',
    'hot-chocolate': 'شوكولاتة ساخنة',
    'green-tea': 'شاي أخضر',
    'black-tea': 'شاي أسود',
    'chai-latte-spiced': 'تشاي لاتيه بالتوابل',
    'chai-latte-vanilla': 'تشاي لاتيه فانيليا',
    'special-tea': 'شاي خاص',
    'matcha': 'ماتشا',
    'vanilla-frappe': 'فرابيه فانيليا',
    'chef-salad': 'سلطة الشيف',
    'greek-salad': 'سلطة يونانية',
    'caesar-salad': 'سلطة سيزر',
    'smoked-salmon-salad': 'سلطة السلمون المدخن',
    'mushroom-soup': 'شوربة فطر',
    'seafood-soup': 'شوربة المأكولات البحرية',
    'corn-soup': 'شوربة ذرة',
    
    // Product Descriptions
    'red-eye-desc': 'قهوة قوية مع جرعة إسبريسو',
    'v60-desc': 'قهوة مختصة بالتقطير',
    'flat-white-desc': 'إسبريسو ناعم بحليب مبخر ورغوة قليلة',
    'espresso-macchiato-desc': 'إسبريسو برغوة حليب مبخرة',
    'marshmallow-hot-chocolate-desc': 'شوكولاتة ساخنة غنية بالمارشملو',
    'turkish-coffee-single-desc': 'قهوة تركية تقليدية محضرة في إبريق نحاسي أصيل',
    'double-espresso-desc': 'جرعة مضاعفة من الإسبريسو الغني لتجربة القهوة المثلى',
    'eggs-of-your-choice-desc': 'بيض طازج محضر كما تشاء تماماً',
    'halloumi-croissant-desc': 'كرواسان بالزبدة محشو بجبنة الحلومي المشوية',
    'tuna-sandwich-desc': 'ساندويش سلطة تونة طازجة مع خضار مقرمشة',
    'manakish-labneh-rocca-desc': 'خبز شرق أوسطي تقليدي باللبنة وأوراق الجرجير',
    'zaatar-pomegranate-desc': 'خبز زعتر تقليدي مع دبس الرمان',
    'manakish-falafel-desc': 'مناقيش فلافل تقليدية',
    'manakish-nabulsi-cheese-desc': 'مناقيش جبن نابلسي أصيل',
    'manakish-zaatar-vegetables-desc': 'مناقيش زعتر مع الخضار الطازجة',
    'marshmallow-chocolate-desc': 'شوكولاتة ساخنة غنية مع المارشمالو',

    'manakish-mix-cheese-desc': 'مناقيش جبن مشكل لذيذة',
    'manakish-molasses-tahini-desc': 'مناقيش دبس وطحينة تقليدية',
    'chicken-bbq-pizza-desc': 'بيتزا دجاج بالباربكيو مع قطع الدجاج الطرية وصلصة الباربكيو',
    'pizza-margherita-desc': 'بيتزا إيطالية كلاسيكية بالموزاريلا الطازجة والطماطم والريحان',
    'pepperoni-pizza-desc': 'بيتزا بيبروني كلاسيكية مع شرائح البيبروني الحارة',
    'mix-formaggio-desc': 'بيتزا الجبن المشكل مع أربعة أنواع مختلفة من الجبن',
    'pizza-chicken-alfredo-desc': 'بيتزا ألفريدو الكريمية مع الدجاج المشوي',
    'calzone-pizza-desc': 'بيتزا إيطالية تقليدية مطوية مع الجبن والحشوات',
    'pepperoni-desc': 'بيتزا بيبروني كلاسيكية مع شرائح البيبروني الحارة',
    'oak-steak-desc': 'ستيك لحم بقري فاخر مشوي للكمال',
    'salmon-grill-desc': 'سلمون طازج مشوي بالأعشاب والليمون',
    'beef-steak-desc': 'ستيك لحم بقري طري مطبوخ حسب تفضيلك',
    'chicken-mushroom-desc': 'صدر دجاج مشوي مع صلصة الفطر',
    'club-sandwich-desc': 'ساندويش كلوب كلاسيكي مع الديك الرومي والبيكون والخس والطماطم',
    'chicken-sandwich-desc': 'ساندويش دجاج مشوي مع خضار طازجة وصلصة خاصة',
    'grilled-cheese-desc': 'ساندويش جبن مشوي ذهبي مع جبن مذاب وخبز مقرمش',
    'oak-beef-burger-desc': 'برغر لحم بقري فاخر مع خضار طازجة وصلصتنا المميزة',
    'crispy-chicken-burger-desc': 'برغر دجاج مقلي مقرمش مع إضافات طازجة',
    'shawarma-meat-desc': 'شاورما شرق أوسطية تقليدية بلحم متبل',
    'oak-sandwich-desc': 'ساندويشنا المميز بمكونات فاخرة',
    'fettuccine-alfredo-desc': 'باستا إيطالية كلاسيكية مع صلصة ألفريدو الكريمية',
    'spaghetti-bolognese-desc': 'سباغيتي تقليدية مع صلصة اللحم الغنية',
    'penne-arrabbiata-desc': 'باستا حارة مع صلصة الطماطم والفلفل الحار',
    'seafood-pasta-desc': 'باستا طازجة مع ثمار البحر المشكلة في صلصة الطماطم',
    'pesto-pasta-desc': 'باستا مع صلصة البيستو الطازجة',
    'lasagna-desc': 'لازانيا تقليدية بطبقات مع صلصة اللحم والجبن',
    'rose-pasta-desc': 'باستا مع صلصة الوردة الكريمية',
    'mac-and-cheese-desc': 'ماكاروني كلاسيكي مع صلصة الجبن الكريمية',

    'fattoush-salad-desc': 'سلطة شرق أوسطية مع خضار مشكلة وخبز مقرمش',
    'tabbouleh-salad-desc': 'سلطة بقدونس طازجة مع الطماطم والبرغل',
    'quinoa-salad-desc': 'سلطة كينوا صحية مع خضار طازجة',
    'chicken-wings-desc': 'أجنحة دجاج مقرمشة مع صلصة خاصة',
    'mozzarella-sticks-desc': 'أصابع جبن موزاريلا مقلية ذهبية',
    'onion-rings-desc': 'حلقات بصل مقرمشة مغطاة بالعجين',
    'dynamite-shrimp-desc': 'جمبري حار مع صلصة ديناميت',
    'chicken-dynamite-desc': 'دجاج مقرمش مع صلصة ديناميت الحارة',
    'mexican-nachos-desc': 'رقائق تورتيلا مع الجبن والفلفل الحار والإضافات',
    'hash-browns-desc': 'بطاطس هاش براون ذهبية مقرمشة',
    'french-toast-desc': 'توست فرنسي كلاسيكي مع الشراب',
    'pancakes-desc': 'بان كيك طري مع الشراب والزبدة',
    'waffles-desc': 'وافل ذهبي مع الشراب',
    'chocolate-milkshake-desc': 'ميلك شيك شوكولاتة غني',
    'vanilla-milkshake-desc': 'ميلك شيك فانيليا كريمي',
    'strawberry-milkshake-desc': 'ميلك شيك فراولة طازجة',
    'caramel-frappe-desc': 'قهوة مثلجة بنكهة الكراميل',

    'chocolate-frappe-desc': 'قهوة مثلجة بنكهة الشوكولاتة',
    'mango-smoothie-desc': 'سموذي مانجو طازج',
    'berry-smoothie-desc': 'سموذي توت مشكل',
    'banana-smoothie-desc': 'سموذي موز كريمي',
    'lemon-mojito-desc': 'موهيتو ليمون منعش',
    'mint-mojito-desc': 'موهيتو نعناع طازج',
    'watermelon-juice-desc': 'عصير بطيخ طازج',
    'apple-juice-desc': 'عصير تفاح طازج',
    'carrot-juice-desc': 'عصير جزر طازج',

    'chamomile-tea-desc': 'شاي بابونج مهدئ',
    'earl-grey-tea-desc': 'شاي إيرل جراي التقليدي',
    'tiramisu-cake-desc': 'حلوى إيطالية كلاسيكية مع القهوة والماسكاربوني',
    'cheesecake-desc': 'تشيز كيك غني وكريمي',
    'chocolate-cake-desc': 'كيك شوكولاتة فاخر',
    'san-sebastian-cake-desc': 'تشيز كيك إسباني محروق',
    'v60-chemex-desc': 'طرق تحضير قهوة مختصة بالتقطير في٦٠ أو كيمكس',
    'caramel-macchiato-desc': 'إسبريسو بنكهة الكراميل وحليب مبخر',
    'lungo-desc': 'جرعة إسبريسو طويلة بماء أكثر لطعم أخف',
    'white-coffee-desc': 'قهوة بيضاء تقليدية مع حليب مكثف',
    'sandy-chocolate-desc': 'مشروب شوكولاتة غني بملمس رملي فريد',
    'filter-coffee-desc': 'قهوة بالتقطير الكلاسيكية محضرة بدقة',
    'white-mocha-desc': 'موكا شوكولاتة بيضاء كريمية مع إسبريسو',
    'chili-chocolate-desc': 'مشروب شوكولاتة حار مع لمسة من الفلفل الحار',
    'spanish-latte-desc': 'لاتيه إسبانية مع حليب مكثف',
    'dark-mocha-desc': 'موكا شوكولاتة داكنة غنية مع إسبريسو',
    'iced-caramel-macchiato-desc': 'كراميل ماكياتو مبرد على الثلج',
    'iced-dark-mocha-desc': 'موكا شوكولاتة داكنة باردة على الثلج',
    'iced-flat-white-desc': 'قهوة فلات وايت مبردة على الثلج',
    'iced-white-mocha-desc': 'موكا شوكولاتة بيضاء باردة على الثلج',
    'cold-brew-desc': 'قهوة مخمرة باردة ناعمة تقدم مبردة',
    'iced-americano-desc': 'أمريكانو كلاسيكي يقدم على الثلج',
    'iced-latte-desc': 'لاتيه مثلج كريمي مع حليب مبخر',
    'iced-spanish-latte-desc': 'لاتيه إسبانية مبردة مع حليب مكثف',
    'hazelnut-frappe-desc': 'قهوة مثلجة مخلوطة بنكهة البندق',
    'white-fruit-frappe-desc': 'خليط فرابيه فواكه بيضاء',
    'white-chocolate-frappe-desc': 'شوكولاتة بيضاء كريمية مخلوطة مع الثلج',
    'coffee-frappe-desc': 'فرابيه قهوة كلاسيكي مخلوط مع الثلج',
    'arabia-milkshake-desc': 'ميلك شيك تقليدي بالطريقة العربية',
    'lemon-milkshake-desc': 'ميلك شيك بنكهة الليمون الحامضة',
    'caramel-milkshake-desc': 'ميلك شيك كراميل حلو',
    'mango-milkshake-desc': 'ميلك شيك مانجو استوائي',
    'mix-berries-smoothie-desc': 'سموذي توت مشكل غني بمضادات الأكسدة',
    'lemonade-smoothie-desc': 'خليط سموذي ليمونادة منعش',
    'mango-passionfruit-smoothie-desc': 'خليط استوائي من المانجو وباشن فروت',
    'lemon-mint-smoothie-desc': 'سموذي ليمون ونعناع منعش',
    'basil-lemonade-smoothie-desc': 'سموذي ليمونادة فريد بالريحان',
    'orange-smoothie-desc': 'سموذي برتقال طازج مليء بفيتامين سي',
    'mango-mint-juice-desc': 'عصير مانجو طازج مع أوراق النعناع',
    'basil-lemonade-juice-desc': 'عصير ليمونادة عطري بالريحان',
    'lemon-mint-juice-desc': 'عصير ليمون منعش مع نعناع طازج',
    'lemonade-juice-desc': 'ليمونادة طازجة كلاسيكية',
    'pomegranate-juice-desc': 'عصير رمان غني بمضادات الأكسدة',
    'mango-basil-juice-desc': 'عصير مانجو غريب مع ريحان طازج',
    'forest-mojito-desc': 'موهيتو عشبي مستوحى من الغابة',
    'mango-mojito-desc': 'موهيتو مانجو استوائي',
    'pink-lemonade-desc': 'ليمونادة وردية حلوة بنكهة التوت',
    'red-sea-redbull-desc': 'مشروب طاقة ريد بول بنكهة البحر الأحمر',
    'maldives-redbull-desc': 'ريد بول استوائي مستوحى من المالديف',
    'ice-tea-peach-desc': 'شاي مثلج منعش بالخوخ',
    'iced-tea-mango-desc': 'شاي مثلج استوائي بالمانجو',
    'iced-tea-sugar-free-desc': 'خيار شاي مثلج خالي من السكر',
    'iced-tea-strawberry-desc': 'شاي مثلج حلو بالفراولة',
    'iced-tea-grenadine-desc': 'شاي مثلج مع شراب الجرانادين',
    'classic-iced-tea-desc': 'شاي مثلج تقليدي يقدم مبرداً',
    'fanta-desc': 'مشروب غازي كلاسيكي بنكهة البرتقال',
    'mix-platter-desc': 'طبق مقبلات متنوع مع مختارات متنوعة',
    'kenafa-naama-desc': 'حلوى شرق أوسطية تقليدية بالجبن والشراب',
    'ice-cream-vanilla-desc': 'آيس كريم فانيليا كلاسيكي',
    'ice-cream-chocolate-desc': 'آيس كريم شوكولاتة غني',
    'ice-cream-strawberry-desc': 'آيس كريم فراولة طازج',
    'tiramisu-desc': 'حلوى إيطالية كلاسيكية مع القهوة والماسكاربوني',




    'turkey-omelette-croissant-desc': 'كرواسون هش مع ديك رومي وأومليت',
    'avocado-omelette-desc': 'أومليت صحي مع أفوكادو طازج',
    'turkey-croissant-desc': 'كرواسون محشو بشرائح ديك رومي فاخرة',
    'classic-mojito-desc': 'موهيتو تقليدي مع نعناع طازج',
    'strawberry-mojito-desc': 'موهيتو منعش بنكهة الفراولة',
    'passion-fruit-mojito-desc': 'موهيتو غريب مع باشن فروت',
    'ice-tea-forest-desc': 'مزيج شاي مثلج بنكهة الغابة',
    'ice-tea-passion-fruit-desc': 'شاي مثلج باشن فروت',
    'coca-cola-desc': 'مشروب كوكا كولا الكلاسيكي',
    'coca-cola-zero-desc': 'كوكا كولا خالية من السكر',
    'sprite-desc': 'مشروب غازي بنكهة الليمون والليم',
    'sprite-zero-desc': 'مشروب ليمون وليم خالي من السكر',
    'mineral-water-desc': 'مياه معدنية نقية',
    'perrier-desc': 'مياه معدنية طبيعية فوارة',
    'red-bull-desc': 'مشروب طاقة مع كافيين وتورين',
    'redbull-sugar-free-desc': 'مشروب طاقة خالي من السكر',
    'hot-chocolate-desc': 'شوكولاتة ساخنة غنية وكريمية',
    'green-tea-desc': 'شاي أخضر غني بمضادات الأكسدة',
    'black-tea-desc': 'شاي أسود كلاسيكي',
    'chai-latte-spiced-desc': 'تشاي لاتيه بالتوابل العطرية',
    'chai-latte-vanilla-desc': 'تشاي لاتيه بنكهة الفانيليا',
    'special-tea-desc': 'مزيج الشاي الخاص المميز',
    'matcha-desc': 'شاي ماتشا أخضر ياباني فاخر',
    'vanilla-frappe-desc': 'فرابيه فانيليا كريمي مخلوط مع الثلج',
    'chef-salad-desc': 'خضار ورقية مشكلة مع مكونات الشيف الخاصة والصلصة',
    'greek-salad-desc': 'سلطة يونانية تقليدية مع جبن الفيتا والزيتون',
    'caesar-salad-desc': 'سلطة سيزر كلاسيكية مع خس رومان وجبن البارميزان',
    'smoked-salmon-salad-desc': 'سلطة طازجة مع سلمون مدخن فاخر',
    'mushroom-soup-desc': 'شوربة فطر كريمية مع أعشاب طازجة',
    'seafood-soup-desc': 'شوربة مأكولات بحرية غنية مع مزيج من خيرات البحر',
    'corn-soup-desc': 'شوربة ذرة حلوة مع قاعدة كريمية',
    'oak-seasonal-juice-desc': 'مزيجنا الموسمي المميز من أطيب الفواكه المتوفرة',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    // Save language to localStorage and update document direction
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};